spring:
  application:
    name: sql-trainer

  data:
    mongodb:
      uri: ${MONGO-URI:mongodb://localhost:27017/sql-trainer}

    postgres:
      jdbcUrl: ${POSTGRES-URL:jdbc:postgresql://localhost:5432/my_db}
      username: ${POSTGRES-USER:root}
      password: ${POSTGRES-PASSWORD:root}
      driver-class-name: org.postgresql.Driver

    postgres-test:
      jdbcUrl: ${POSTGRES-TEST-URL:jdbc:postgresql://localhost:5432/sql_trainer}
      username: ${POSTGRES-USER:root}
      password: ${POSTGRES-PASSWORD:root}
      driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false
    liquibase-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  main:
    web-application-type: servlet

sqltrainer:
  application:
    jwt:
      secret: ${JWT-SECRET:2d9fc0cb9a1a451208e231a67f00e7dfb664ac93dbc9fbbb36e891f5a9a568a35acaf2dbc21199745d7de4e94e83547d41929f2ca1325406b7448fb868602d510ac444e80825df4b4f81ce4439a28c71a64e71873cc791008ac36ad8228e20c2ff9db679d52df9e06a94e7ea2a7a7a2ef7fe6f2011342d165faff5779a73dad42ded6c1babaf87f0ccfa1710d2565d5e33cda3f938e329781bc2dadbecfbf9683ee61e1f7b5650ead08e3ce2b6c37ac2ec19f9ff17403e073a962a36c325a41044f9f8db019d0a83741ff29301dcd67750074b563403c7ed9fffea7c4db8965daefe4f6b107ef91f064f2fa4d0a7d08ee0f4f8b7f780cac6dc16f7e27800f426}
      expireTimeMs: ${JWT-EXPIRE:86400000}

  security:
    defaultAdminEmail: ${DEFAULT-ADMIN-EMAIL:admin@yandex.ru}
    defaultAdminPassword: ${DEFAULT-ADMIN-PASSWORD:admin}